pkg_origin=fenrirunbound
pkg_name=mplater
pkg_version=0.1.0
pkg_maintainer="Darren Matsumoto <aeneascorrupt@gmail.com>"
pkg_scaffolding=core/scaffolding-go
pkg_source="https://github.com/FenrirUnbound/mplater"
pkg_upstream_url=https://github.com/FenrirUnbound/mplater
pkg_deps=(core/go)
pkg_exports=()
pkg_bin_dirs=()
pkg_exposes=()
