workflow:
- deploy

shared:
  image: golang:1.7
  environment:
    GOPATH: /sd/workspace

jobs:
  main:
    steps:
    - huh: sd-step exec fenrirunbound/mplater "mplater -h"
    - follow: mplater -h

  deploy:
    steps:
    - setup-ci: git clone https://gist.github.com/3d2388b2a7ba658cdcdaffa8cd874e50.git /tmp/ci
    - get: go get -t ./...
    - tag: /tmp/ci/git-tag.sh
    - release: |
        rm ./VERSION
        curl -sL https://git.io/goreleaser | bash
    secrets:
    - GIT_KEY
    # Pushing releases to GitHub
    - GITHUB_TOKEN
    environment:
      RELEASE_FILE: mplater
