workflow:
- deploy

shared:
  image: golang
  environment:
    GOPATH: /sd/workspace

jobs:
  main:
    steps:
    - get: go get -t ./...
    - vet: go vet ./...
    - gofmt: "find . -name '*.go' | xargs gofmt -s -w"
    - test: go test ./...
    - build: go build -a -o mplater

  deploy:
    steps:
    - setup-ci: git clone https://gist.github.com/3d2388b2a7ba658cdcdaffa8cd874e50.git ci
    - get: go get -t ./...
    - gofmt: "find . -name '*.go' | xargs gofmt -s -w"
    - build: go build -a -o mplater
    - tag: ./ci/git-tag.sh
    - release: curl -sL https://git.io/goreleaser | bash
    secrets:
    - GIT_KEY
    # Pushing releases to GitHub
    - GITHUB_TOKEN
    environment:
      RELEASE_FILE: mplater
