shared:
  image: golang
  environment:
    GOPATH: /sd/workspace
    GO15VENDOREXPERIMENT: 1

jobs:
  main:
    requires:
    - ~commit
    - ~pr
    steps:
    - get: go get -t ./...
    - vet: go vet $(go list ./... | grep -v /vendor/)
    - gofmt: go fmt $(go list ./... | grep -v /vendor/)
    - test: go test $(go list ./... | grep -v /vendor/)
    - build: go build -a -o mplater

  deploy:
    requires:
    - main
    steps:
    - setup-ci: git clone https://github.com/screwdriver-cd/toolbox /tmp/ci
    - get: go get -t ./...
    - tag: /tmp/ci/git-tag.sh
    - release: |
        rm ./VERSION
        curl -sL https://git.io/goreleaser | bash
    secrets:
    - GIT_KEY
    # Pushing releases to GitHub
    - GITHUB_TOKEN
    environment:
      RELEASE_FILE: mplater
