---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myserver
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: myapplication
        tier: api
    spec:
      containers:
      - name: myserver
        image: screwdrivercd/screwdriver:v4.0.100
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /api/status
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
